
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.func
{
public partial class DropRuleTable
{
    private readonly System.Collections.Generic.Dictionary<int, func.DropRule> _dataMap;
    private readonly System.Collections.Generic.List<func.DropRule> _dataList;
    
    public DropRuleTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, func.DropRule>();
        _dataList = new System.Collections.Generic.List<func.DropRule>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            func.DropRule _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = func.DropRule.DeserializeDropRule(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, func.DropRule> DataMap => _dataMap;
    public System.Collections.Generic.List<func.DropRule> DataList => _dataList;

    public func.DropRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public func.DropRule Get(int key) => _dataMap[key];
    public func.DropRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

