
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.func
{
public partial class inspectionTable
{
    private readonly System.Collections.Generic.Dictionary<int, func.inspection> _dataMap;
    private readonly System.Collections.Generic.List<func.inspection> _dataList;
    
    public inspectionTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, func.inspection>();
        _dataList = new System.Collections.Generic.List<func.inspection>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            func.inspection _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = func.inspection.Deserializeinspection(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, func.inspection> DataMap => _dataMap;
    public System.Collections.Generic.List<func.inspection> DataList => _dataList;

    public func.inspection GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public func.inspection Get(int key) => _dataMap[key];
    public func.inspection this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

