
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cha
{
public partial class CharacterTable
{
    private readonly System.Collections.Generic.Dictionary<int, cha.Character> _dataMap;
    private readonly System.Collections.Generic.List<cha.Character> _dataList;
    
    public CharacterTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cha.Character>();
        _dataList = new System.Collections.Generic.List<cha.Character>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cha.Character _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cha.Character.DeserializeCharacter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cha.Character> DataMap => _dataMap;
    public System.Collections.Generic.List<cha.Character> DataList => _dataList;

    public cha.Character GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cha.Character Get(int key) => _dataMap[key];
    public cha.Character this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

