
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.text
{
public sealed partial class Localization : Luban.BeanBase
{
    public Localization(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Zh"].IsString) { throw new SerializationException(); }  Zh = _buf["Zh"]; }
        { if(!_buf["En"].IsString) { throw new SerializationException(); }  En = _buf["En"]; }
        { if(!_buf["Ja"].IsString) { throw new SerializationException(); }  Ja = _buf["Ja"]; }
    }

    public static Localization DeserializeLocalization(JSONNode _buf)
    {
        return new text.Localization(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Zh;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 日文
    /// </summary>
    public readonly string Ja;
   
    public const int __ID__ = -1211199014;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Zh:" + Zh + ","
        + "En:" + En + ","
        + "Ja:" + Ja + ","
        + "}";
    }
}

}

