
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.scene
{
public partial class RoomsTable
{
    private readonly System.Collections.Generic.Dictionary<int, scene.Rooms> _dataMap;
    private readonly System.Collections.Generic.List<scene.Rooms> _dataList;
    
    public RoomsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, scene.Rooms>();
        _dataList = new System.Collections.Generic.List<scene.Rooms>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            scene.Rooms _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = scene.Rooms.DeserializeRooms(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, scene.Rooms> DataMap => _dataMap;
    public System.Collections.Generic.List<scene.Rooms> DataList => _dataList;

    public scene.Rooms GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public scene.Rooms Get(int key) => _dataMap[key];
    public scene.Rooms this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

