
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.interact
{
public partial class InteractEffectTable
{
    private readonly System.Collections.Generic.Dictionary<int, interact.InteractEffect> _dataMap;
    private readonly System.Collections.Generic.List<interact.InteractEffect> _dataList;
    
    public InteractEffectTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, interact.InteractEffect>();
        _dataList = new System.Collections.Generic.List<interact.InteractEffect>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            interact.InteractEffect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = interact.InteractEffect.DeserializeInteractEffect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, interact.InteractEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<interact.InteractEffect> DataList => _dataList;

    public interact.InteractEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public interact.InteractEffect Get(int key) => _dataMap[key];
    public interact.InteractEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

