
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.skill
{
public partial class ActiveSkillsTable
{
    private readonly System.Collections.Generic.Dictionary<int, skill.ActiveSkills> _dataMap;
    private readonly System.Collections.Generic.List<skill.ActiveSkills> _dataList;
    
    public ActiveSkillsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.ActiveSkills>();
        _dataList = new System.Collections.Generic.List<skill.ActiveSkills>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            skill.ActiveSkills _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = skill.ActiveSkills.DeserializeActiveSkills(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skill.ActiveSkills> DataMap => _dataMap;
    public System.Collections.Generic.List<skill.ActiveSkills> DataList => _dataList;

    public skill.ActiveSkills GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skill.ActiveSkills Get(int key) => _dataMap[key];
    public skill.ActiveSkills this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

