
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.skill
{
public sealed partial class ActiveSkills : Luban.BeanBase
{
    public ActiveSkills(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["NAME"].IsNumber) { throw new SerializationException(); }  NAME = _buf["NAME"]; }
        { if(!_buf["DESCRIBE"].IsNumber) { throw new SerializationException(); }  DESCRIBE = _buf["DESCRIBE"]; }
        { if(!_buf["skillCD"].IsNumber) { throw new SerializationException(); }  SkillCD = _buf["skillCD"]; }
        { if(!_buf["SkillSanCost"].IsNumber) { throw new SerializationException(); }  SkillSanCost = _buf["SkillSanCost"]; }
        { if(!_buf["SkillEffectID"].IsNumber) { throw new SerializationException(); }  SkillEffectID = _buf["SkillEffectID"]; }
    }

    public static ActiveSkills DeserializeActiveSkills(JSONNode _buf)
    {
        return new skill.ActiveSkills(_buf);
    }

    public readonly int ID;
    public readonly int NAME;
    public readonly int DESCRIBE;
    public readonly int SkillCD;
    public readonly int SkillSanCost;
    /// <summary>
    /// 技能效果
    /// </summary>
    public readonly int SkillEffectID;
   
    public const int __ID__ = -179974267;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NAME:" + NAME + ","
        + "DESCRIBE:" + DESCRIBE + ","
        + "skillCD:" + SkillCD + ","
        + "SkillSanCost:" + SkillSanCost + ","
        + "SkillEffectID:" + SkillEffectID + ","
        + "}";
    }
}

}

