
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.mon
{
public partial class MonsterTable
{
    private readonly System.Collections.Generic.Dictionary<int, mon.Monster> _dataMap;
    private readonly System.Collections.Generic.List<mon.Monster> _dataList;
    
    public MonsterTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, mon.Monster>();
        _dataList = new System.Collections.Generic.List<mon.Monster>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            mon.Monster _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = mon.Monster.DeserializeMonster(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, mon.Monster> DataMap => _dataMap;
    public System.Collections.Generic.List<mon.Monster> DataList => _dataList;

    public mon.Monster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public mon.Monster Get(int key) => _dataMap[key];
    public mon.Monster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

