
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class FoodTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.Food> _dataMap;
    private readonly System.Collections.Generic.List<item.Food> _dataList;
    
    public FoodTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Food>();
        _dataList = new System.Collections.Generic.List<item.Food>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.Food _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.Food.DeserializeFood(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.Food> DataMap => _dataMap;
    public System.Collections.Generic.List<item.Food> DataList => _dataList;

    public item.Food GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Food Get(int key) => _dataMap[key];
    public item.Food this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

