
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class GameObjectsTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.MyGameObejcts> _dataMap;
    private readonly System.Collections.Generic.List<item.MyGameObejcts> _dataList;
    
    public GameObjectsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.MyGameObejcts>();
        _dataList = new System.Collections.Generic.List<item.MyGameObejcts>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.MyGameObejcts _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.MyGameObejcts.DeserializeMyGameObejcts(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.MyGameObejcts> DataMap => _dataMap;
    public System.Collections.Generic.List<item.MyGameObejcts> DataList => _dataList;

    public item.MyGameObejcts GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.MyGameObejcts Get(int key) => _dataMap[key];
    public item.MyGameObejcts this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

