
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class JewelryTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.Jewelry> _dataMap;
    private readonly System.Collections.Generic.List<item.Jewelry> _dataList;
    
    public JewelryTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Jewelry>();
        _dataList = new System.Collections.Generic.List<item.Jewelry>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.Jewelry _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.Jewelry.DeserializeJewelry(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.Jewelry> DataMap => _dataMap;
    public System.Collections.Generic.List<item.Jewelry> DataList => _dataList;

    public item.Jewelry GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Jewelry Get(int key) => _dataMap[key];
    public item.Jewelry this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

