
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class RewardTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.Reward> _dataMap;
    private readonly System.Collections.Generic.List<item.Reward> _dataList;
    
    public RewardTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Reward>();
        _dataList = new System.Collections.Generic.List<item.Reward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.Reward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.Reward.DeserializeReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.Reward> DataMap => _dataMap;
    public System.Collections.Generic.List<item.Reward> DataList => _dataList;

    public item.Reward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Reward Get(int key) => _dataMap[key];
    public item.Reward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

