
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class TableEquipable : Luban.BeanBase
{
    public TableEquipable(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
        { if(!_buf["atkIncrese"].IsNumber) { throw new SerializationException(); }  AtkIncrese = _buf["atkIncrese"]; }
    }

    public static TableEquipable DeserializeTableEquipable(JSONNode _buf)
    {
        return new item.TableEquipable(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 物品名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 属性增强
    /// </summary>
    public readonly int AtkIncrese;
   
    public const int __ID__ = -939511369;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "price:" + Price + ","
        + "atkIncrese:" + AtkIncrese + ","
        + "}";
    }
}

}

