
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class ThrowObjectsTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.ThrowObjects> _dataMap;
    private readonly System.Collections.Generic.List<item.ThrowObjects> _dataList;
    
    public ThrowObjectsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.ThrowObjects>();
        _dataList = new System.Collections.Generic.List<item.ThrowObjects>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.ThrowObjects _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.ThrowObjects.DeserializeThrowObjects(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.ThrowObjects> DataMap => _dataMap;
    public System.Collections.Generic.List<item.ThrowObjects> DataList => _dataList;

    public item.ThrowObjects GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.ThrowObjects Get(int key) => _dataMap[key];
    public item.ThrowObjects this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

