
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class ThrowObjects : Luban.BeanBase
{
    public ThrowObjects(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["NAME"].IsString) { throw new SerializationException(); }  NAME = _buf["NAME"]; }
        { if(!_buf["DESCRIBE"].IsString) { throw new SerializationException(); }  DESCRIBE = _buf["DESCRIBE"]; }
        { if(!_buf["interactEffectID"].IsNumber) { throw new SerializationException(); }  InteractEffectID = _buf["interactEffectID"]; }
        { if(!_buf["isDestructible"].IsBoolean) { throw new SerializationException(); }  IsDestructible = _buf["isDestructible"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
    }

    public static ThrowObjects DeserializeThrowObjects(JSONNode _buf)
    {
        return new item.ThrowObjects(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NAME;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string DESCRIBE;
    /// <summary>
    /// 玩家与其的交互是哪一种
    /// </summary>
    public readonly int InteractEffectID;
    /// <summary>
    /// 是否可被破坏
    /// </summary>
    public readonly bool IsDestructible;
    /// <summary>
    /// 物品重量
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
   
    public const int __ID__ = 635118185;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NAME:" + NAME + ","
        + "DESCRIBE:" + DESCRIBE + ","
        + "interactEffectID:" + InteractEffectID + ","
        + "isDestructible:" + IsDestructible + ","
        + "weight:" + Weight + ","
        + "attack:" + Attack + ","
        + "}";
    }
}

}

