
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class TinyObjectsTable
{
    private readonly System.Collections.Generic.Dictionary<int, item.TinyObjects> _dataMap;
    private readonly System.Collections.Generic.List<item.TinyObjects> _dataList;
    
    public TinyObjectsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.TinyObjects>();
        _dataList = new System.Collections.Generic.List<item.TinyObjects>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item.TinyObjects _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item.TinyObjects.DeserializeTinyObjects(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.TinyObjects> DataMap => _dataMap;
    public System.Collections.Generic.List<item.TinyObjects> DataList => _dataList;

    public item.TinyObjects GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.TinyObjects Get(int key) => _dataMap[key];
    public item.TinyObjects this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

