
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class Tools : Luban.BeanBase
{
    public Tools(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["NAME"].IsString) { throw new SerializationException(); }  NAME = _buf["NAME"]; }
        { if(!_buf["DESCRIBE"].IsString) { throw new SerializationException(); }  DESCRIBE = _buf["DESCRIBE"]; }
        { if(!_buf["prefabName"].IsString) { throw new SerializationException(); }  PrefabName = _buf["prefabName"]; }
        { if(!_buf["interactEffectID"].IsNumber) { throw new SerializationException(); }  InteractEffectID = _buf["interactEffectID"]; }
        { if(!_buf["derubility"].IsNumber) { throw new SerializationException(); }  Derubility = _buf["derubility"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["IconName"].IsString) { throw new SerializationException(); }  IconName = _buf["IconName"]; }
    }

    public static Tools DeserializeTools(JSONNode _buf)
    {
        return new item.Tools(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NAME;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string DESCRIBE;
    /// <summary>
    /// 预制体名称
    /// </summary>
    public readonly string PrefabName;
    /// <summary>
    /// 物品在地上时，玩家与其的交互是哪一种
    /// </summary>
    public readonly int InteractEffectID;
    /// <summary>
    /// 耐久
    /// </summary>
    public readonly int Derubility;
    /// <summary>
    /// 注意，更详细的功能效果并未配进该表中
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 图标名称
    /// </summary>
    public readonly string IconName;
   
    public const int __ID__ = 911370016;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NAME:" + NAME + ","
        + "DESCRIBE:" + DESCRIBE + ","
        + "prefabName:" + PrefabName + ","
        + "interactEffectID:" + InteractEffectID + ","
        + "derubility:" + Derubility + ","
        + "weight:" + Weight + ","
        + "IconName:" + IconName + ","
        + "}";
    }
}

}

