
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.buff
{ 
    public enum BuffEnum
    {
        中毒 = 120001,
        灵视 = 120002,
        寄生 = 120003,
        严重寄生 = 120004,
        完全寄生 = 120005,
        美德 = 120006,
        疯狂 = 120007,
        惊恐 = 120008,
        飞奔 = 120009,
        癫狂1 = 120012,
        癫狂2 = 120013,
        癫狂3 = 120014,
    }

} 

