
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.buff
{
public sealed partial class Conditions : Luban.BeanBase
{
    public Conditions(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["NAME"].IsString) { throw new SerializationException(); }  NAME = _buf["NAME"]; }
        { if(!_buf["DESCRIBE"].IsString) { throw new SerializationException(); }  DESCRIBE = _buf["DESCRIBE"]; }
        { if(!_buf["canTimeStack"].IsBoolean) { throw new SerializationException(); }  CanTimeStack = _buf["canTimeStack"]; }
        { if(!_buf["maxTime"].IsNumber) { throw new SerializationException(); }  MaxTime = _buf["maxTime"]; }
    }

    public static Conditions DeserializeConditions(JSONNode _buf)
    {
        return new buff.Conditions(_buf);
    }

    /// <summary>
    /// 序号
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string NAME;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string DESCRIBE;
    /// <summary>
    /// 再次获得时，是否叠加持续时间，如果不叠加，则取持续时间更长的那一个
    /// </summary>
    public readonly bool CanTimeStack;
    /// <summary>
    /// 可堆叠的最大时间上限<br/>
    /// </summary>
    public readonly int MaxTime;
   
    public const int __ID__ = -1178173613;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "NAME:" + NAME + ","
        + "DESCRIBE:" + DESCRIBE + ","
        + "canTimeStack:" + CanTimeStack + ","
        + "maxTime:" + MaxTime + ","
        + "}";
    }
}

}

