
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.buff
{
public partial class ConditionsTable
{
    private readonly System.Collections.Generic.Dictionary<int, buff.Conditions> _dataMap;
    private readonly System.Collections.Generic.List<buff.Conditions> _dataList;
    
    public ConditionsTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, buff.Conditions>();
        _dataList = new System.Collections.Generic.List<buff.Conditions>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            buff.Conditions _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = buff.Conditions.DeserializeConditions(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, buff.Conditions> DataMap => _dataMap;
    public System.Collections.Generic.List<buff.Conditions> DataList => _dataList;

    public buff.Conditions GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public buff.Conditions Get(int key) => _dataMap[key];
    public buff.Conditions this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

