
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Luban;
using SimpleJSON;

///
/// 添加接口编程规范
///
public interface IData
{
    
}

public interface ITable
{
    public IData FindById(int ID);
}

namespace cfg
{
public partial class Tables
{
    public Dictionary<Type, ITable> ITables = new Dictionary<Type, ITable>();
    public item.TableReward TableReward {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TableReward = new item.TableReward(loader("item_tablereward"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TableReward.ResolveRef(this);
        ITables.Add(TableReward.GetType(),TableReward);
    }
}

}
