
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.RewardTable RewardTable {get; }
    public item.GameObjectsTable GameObjectsTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        RewardTable = new item.RewardTable(loader("item_rewardtable"));
        GameObjectsTable = new item.GameObjectsTable(loader("item_gameobjectstable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        RewardTable.ResolveRef(this);
        GameObjectsTable.ResolveRef(this);
    }
}
}
